version: '3'

services:
    user-service:
        build:
            context: .
        depends_on:
            - mongo
            - redis
        restart: on-failure
        ports:
            - '8140:4000'

    mysql:
        image: mysql
        restart: on-failure

    redis:
        image: redis
        restart: on-failure

volumes:
    data: